version: '3.4'

services:

  group18:
    build: ./
    container_name: group18
    command: sh -c "uvicorn app:app --host 0.0.0.0 --port 8006"
    environment: 
      - APP_NAME=group18
    ports:
      - "8006:8006" 
